import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import Logo from "@/elements/Logo/Logo";
import Projects from "@/modules/Projects/Projects";
import Contact from "@/modules/Contact/Contact";
import ThreeScene from "@/elements/canvas/Stars/stars";
import About from "@/modules/About/About";
import Banner from "../modules/Banner/Banner";
import Navigation from "@/modules/Navigation/Navigation";
import { Suspense } from "react";
import CanvasLoader from "@/elements/canvas/Loader/Loader";

export default function Home() {

  
  return (
    <>
      <Head>
        <title>Portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/logoJM.png" />
      </Head>


      <main className={"gradient"}>

        <Navigation />
         <Banner />
        <About />
        <Projects />
        <Contact />
        <ThreeScene />
      </main>

    </>
  );
}
